const articles = [
  {
    name: "dinero-prioridad",
    title: "¿Es el dinero una prioridad?",
    content: [
      `Uno de los errores que con más cariño  recuerdo fue leer "padre rico padre pobre" cuando tenía 18 años. En un momento que me sentía "visionario" por pensar en la posibilidad de ser mi propio jefe, y en la búsqueda de cómo ser "libre financieramente", cayó a mí ésta obra de Robert Kiyosaki (libro de culto que es casi imposible no toparse al ser nuevo en el ambiente emprendedor). `,
      `Ya he mencionado mi tendencia de no solo tocar el agua con los dedos, si no zambullirme de clavado en temas que me empiezan a enganchar. Al leer ese libro era como descubrir una verdad y una tremenda sabiduría que me hacía creer el hombre más despierto y más destinado a hacer cosas grandes, sin saber lo que eso significara. Interpreté como una señal del destino haberlo encontrado en la biblioteca de mi escuela. Aunque en general es un libro con mensaje positivo, en mi caso de mente hiperactiva sin rumbo definido, puso como prioridad algo que actualmente pienso es erróneo: el dinero. `,
      `En otro momento hablaré de lo que a me parece es una cultura de emprendedurismo toxico. En ésta ocasión quiero hablar sobre cómo es un error tener como prioridad la meta de "tener mucho dinero". Parece que en la definición de éxito de la mayoría de las personas, debe llevar entre otras cosas, tener mucho dinero, incluso por lo general sin las otras cosas. Estoy de acuerdo en que el dinero es lo más importante cuando no lo tienes. Se traduce en alimentos, bienes básicos, salud, vida digna, bienestar físico, emocional… pero… ¿qué consecuencia tiene poner como prioridad el hacer dinero, en la mente de alguien?... en mi experiencia: energía, enfoque y tiempo en estudiar temas que resultan genéricos, creer en fuentes de poca trascendencia, lecciones cuyo fin es meramente motivacional, y lo más doloroso, tomar decisiones basadas en “¿cuánto dinero puedo ganar con dicha decisión?”, siempre movido por la ilusión y la emoción que provoca el resultado final. `,
      "La persona a la que le es implantada una meta y filosofía artificial de “éxito = dinero”, motivado por los grandes gurús de dicha búsqueda, deja en segundo plano sus gustos, su desarrollo fuera del estereotipo de persona exitosa (adinerada), se olvida de moldear su propia definición de éxito, y se vuelve seguidor ciego de filosofías mercantiles que se resume en la repetición de algunos mantras.",
      "El dinero no tiene un valor intrínseco, sino que, vale lo que representa. Algunos billetes pueden significar comidas, objetos, tiempo libre, experiencias, estilos de vida, estatus... poder…",
      "Objetivamente es el medio por el cual intercambiamos un trabajo por otro, en realidad no queremos dinero, queremos lo que se puede comprar, lo que se puede conseguir, y lo que nos puede hacer sentir. Pero entonces ¿porque si el valor del dinero no está en sí mismo, porque ponemos en nuestro enfoque billetes y cuentas con números, como medio para conseguir lo que queremos, en vez de enfocarnos en pensar, que trabajo o proyectos de valor tengo que realizar, para recibir a cambio  todo eso que quiero y que vale la cantidad de dinero que me gustaría. ¿Qué estoy dispuesto a realizar, para recibir todo eso que quiero?. ",
      "Otro aspecto aún más importante: que trabajo de valor quiero, me gusta realizar, para cambiarlo por todas esas cosas que quiero conseguir. ¿No es más importante la manera en la que consigues el dinero, que la cantidad misma que consigues?",
      "Existen personas hábiles financieramente, y que genuinamente su misión en la vida y éxito se basó en inteligencia financiera, pero las personas que yo poco a poco fui admirando y añadiendo a mi catálogo de exitosos y con ideas y valores a seguir, les encontré una idea en común que en el momento me resulto algo paradójica: de nadie de ellos fue motor principal la búsqueda de dinero, no se tomaron decisiones de si esto o aquello generaría más. Todos ellos fueron llevados al éxito bajo su propia definición de éxito y por el amor a su propia meta. Y evidentemente, son personas que no tienen carencia de comida, objetos, tiempo libre, experiencias, estilo de vida, estatus, influencia, incluso poder… pero lo más importante, exitosos bajo su propia definición. Deportistas, artistas, empresarios, y personas que ubicamos como exitosas (y ciertamente con mucho dinero), son conocidas por lo que son y por el éxito en su proyecto, a diferencia de los gurús que su proyecto es la comercialización de su propia filosofía de ganar dinero.",
      "Algo que me voló más la cabeza: la verdadera plenitud y trascendencia no necesita de “mucho dinero”. La trascendencia y logro en lo que uno mismo define como éxito es la verdadera riqueza. Y por lo general, cuando alguien es exitoso, y vive una vida en la cual se alinea lo que hace, lo que siente y lo que piensa, no hay “problemas” o dilemas por dinero.  ",
      "No tengo nada en contra de la riqueza, al contrario. Pero entiendo algo de la frase que creo haber escuchado en algún contexto espiritual/reflexivo: “la raíz de todos los males es el dinero”. Y es que complementando, para mí no es el dinero, es la concepción errónea de todo su contexto. Si a mí me llevó a ideologías que ahora considero erróneas, de la idea del dinero como prioridad se parte hacia la delincuencia, a la corrupción, a la perdida de virtudes, de dignidad, de cegamiento hacia rasgos más trascendentes y enriquecedores de un ser humano. ",
      "Para contrastar con todo lo anterior quiero dejar algo en la mesa: yo sigo queriendo “mucho dinero”. Solo que ahora defino “mucho” en mis propios términos, y le doy un lugar importante mas no prioritario a su búsqueda. Sé que solo es una variable más en la ecuación de plenitud. En resumen me repito que el dinero tiene que ser consecuencia de lo exitoso que eres, haciendo lo que haces.",
    ],
  },
  {
    name: "especializarse",
    title: "¿Especialiarse o tener conocimientos generales?",
    content: [`...`, ``],
  },
  {
    name: "dominar-mente",
    title: "La importancia de dominar tu mente",
    content: [`...`, ``],
  },
];

export default articles;
